POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Unite summit",
  "details": "Um evento pra quem é apaixonado por programação",
  "maximumAttendees": 100
}

###

POST http://127.0.0.1:3333/events
Content-Type: application/json

{
  "title": "evento 2",
  "details": "Um evento pra quem é apaixonado por javascript",
  "maximumAttendees": 1
}

###

POST http://127.0.0.1:3333/events/595de9b4-cfe7-4eab-b702-c1d8377e52b1/attendees
Content-Type: application/json

{
  "name": "Moises oliveira",
  "email": "moises@gmail.com"
}

###

GET http:localhost:3333/events/595de9b4-cfe7-4eab-b702-c1d8377e52b1
Content-Type: application/json